### ISSUE TITLE
默认的apt镜像源报50x错误

### ISSUE THREAD

**Issue by 1061700625** [linyqh/NarratoAI#12]
默认`apt`在`update`过程中由于访问的是`deb.debian.org`，经常会中断。
可以在`Dockerfile`中添加更换[清华源](https://mirrors.tuna.tsinghua.edu.cn/help/ubuntu/)的语句，这样又快又不会中断了：

```bash
# 替换为清华源
RUN sed -i 's@http://deb.debian.org/debian@https://mirrors.tuna.tsinghua.edu.cn/debian@g' /etc/apt/sources.list && \
    sed -i 's@http://security.debian.org/debian-security@https://mirrors.tuna.tsinghua.edu.cn/debian-security@g' /etc/apt/sources.list
```

![image](https://github.com/user-attachments/assets/0e79e666-30cb-4fe0-a493-056152c5532b)

![image](https://github.com/user-attachments/assets/c6842cbf-b08e-4123-b75e-bbccba7c0ad5)

---

> 同理，`pip`如果太慢也可以换国内镜像源

**Comment by yeah2569** [comment]
自己安装的时候一直遇到下面这个问题，大佬遇到过么？
402.3 Downloading rpds_py-0.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (354 kB)
402.7 Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
403.0 Downloading smmap-5.0.1-py3-none-any.whl (24 kB)
404.1 ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; s   someone may have tampered with them.
404.1     unknown package:
404.1         Expected sha256 0220fce2a62d71cc5e89617419b6224ddb43f1753b00f68b5c9af8b5f41d38c9      
404.1              Got        42617eac5241ff34028fd4bed5d42b76526e1b00533d25374eabc67c4b33fa6f      
404.1
------
failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1

**Comment by linyqh** [comment]
> ## 自己安装的时候一直遇到下面这个问题，大佬遇到过么？
> 402.3 Downloading rpds_py-0.20.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (354 kB)
> 402.7 Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
> 403.0 Downloading smmap-5.0.1-py3-none-any.whl (24 kB)
> 404.1 ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. If you have updated the package versions, please update the hashes. Otherwise, examine the package contents carefully; s someone may have tampered with them.
> 404.1 unknown package:
> 404.1 Expected sha256 0220fce2a62d71cc5e89617419b6224ddb43f1753b00f68b5c9af8b5f41d38c9
> 404.1 Got 42617eac5241ff34028fd4bed5d42b76526e1b00533d25374eabc67c4b33fa6f
> 404.1
> failed to solve: process "/bin/sh -c pip install --no-cache-dir -r requirements.txt" did not complete successfully: exit code: 1

我没有尝试更换国内源，我是直接使用的国外的 vpn 代理；
